resources:
  jobs:
    customer_sentiment_analysis_with_ai_query_wf:
      name: customer_sentiment_analysis_with_ai_query_wf
      tasks:
        - task_key: Ingestion
          notebook_task:
            notebook_path: 001_Ingestion
            source: GIT
          environment_key: Default
        - task_key: Inference
          depends_on:
            - task_key: Ingestion
          notebook_task:
            notebook_path: 002 Inference
            source: GIT
          environment_key: Default
        - task_key: Serving
          depends_on:
            - task_key: Inference
          notebook_task:
            notebook_path: 003 Serving
            source: GIT
          environment_key: Default
      git_source:
        git_url: https://github.com/mike-dobing_data/sentinment_analyzer_with_ai_functions
        git_provider: gitHub
        git_branch: main
      queue:
        enabled: true
      environments:
        - environment_key: Default
          spec:
            client: "2"
